version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/capstone_project
    overwrite: true
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root

